version: 1.0.{build}
build:
  project: AppVeyor_Support\MyProject.Specs.sln
  verbosity: minimal
  
  
before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - nuget-restore AppVeyor_Support\MyProject.Specs.sln
  
  
test_script:
- ps: vstest.console /logger:Appveyor "C:\projects\specflow-plus-examples\AppVeyor_Support\MyProject.Specs\bin\Debug\MyProject.Specs.dll" /TestAdapterPath:"C:\projects\specflow-plus-examples\AppVeyor_Support\packages"