// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestApplication.UiTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("CalculatorFeature", Description="\t In order to avoid silly mistakes \r\n\tAs a math idiot\r\n\tI want to be told the sum" +
        " of two numbers", SourceFile="Features\\CalculatorFeature.feature", SourceLine=0)]
    public partial class CalculatorFeatureFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "CalculatorFeature.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CalculatorFeature", "\t In order to avoid silly mistakes \r\n\tAs a math idiot\r\n\tI want to be told the sum" +
                    " of two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Basepage is Calculator", new string[] {
                "Browser_Chrome",
                "Browser_IE",
                "Browser_Firefox"}, SourceLine=8)]
        public virtual void BasepageIsCalculator()
        {
            string[] tagsOfScenario = new string[] {
                    "Browser_Chrome",
                    "Browser_IE",
                    "Browser_Firefox"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Basepage is Calculator", null, new string[] {
                        "Browser_Chrome",
                        "Browser_IE",
                        "Browser_Firefox"});
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
 testRunner.Given("I navigated to /", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 11
 testRunner.Then("browser title is Calculator", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        public virtual void AddTwoNumbers(string summandOne, string summandTwo, string result, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Browser_IE",
                    "Browser_Chrome",
                    "Browser_Firefox"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Two Numbers", null, @__tags);
#line 16
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 17
 testRunner.Given("I navigated to /", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 18
 testRunner.And(string.Format("I have entered {0} into summandOne calculator", summandOne), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 19
 testRunner.And(string.Format("I have entered {0} into summandTwo calculator", summandTwo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 20
 testRunner.When("I press add", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 21
 testRunner.Then(string.Format("the result should be {0} on the screen", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 0", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant0()
        {
#line 16
this.AddTwoNumbers("50", "70", "120", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 1", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant1()
        {
#line 16
this.AddTwoNumbers("1", "10", "11", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 2", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant2()
        {
#line 16
this.AddTwoNumbers("43", "12", "55", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 3", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant3()
        {
#line 16
this.AddTwoNumbers("19", "73", "92", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 4", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant4()
        {
#line 16
this.AddTwoNumbers("26", "12", "38", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 5", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant5()
        {
#line 16
this.AddTwoNumbers("49", "15", "64", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 6", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant6()
        {
#line 16
this.AddTwoNumbers("11", "26", "37", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 7", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant7()
        {
#line 16
this.AddTwoNumbers("81", "93", "174", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 8", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant8()
        {
#line 16
this.AddTwoNumbers("69", "90", "159", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 9", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant9()
        {
#line 16
this.AddTwoNumbers("91", "52", "143", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 10", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant10()
        {
#line 16
this.AddTwoNumbers("38", "52", "90", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 11", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant11()
        {
#line 16
this.AddTwoNumbers("73", "6", "79", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 12", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant12()
        {
#line 16
this.AddTwoNumbers("64", "40", "104", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 13", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant13()
        {
#line 16
this.AddTwoNumbers("48", "8", "56", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 14", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant14()
        {
#line 16
this.AddTwoNumbers("93", "25", "118", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 15", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant15()
        {
#line 16
this.AddTwoNumbers("83", "40", "123", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 16", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant16()
        {
#line 16
this.AddTwoNumbers("56", "1", "57", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 17", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant17()
        {
#line 16
this.AddTwoNumbers("70", "88", "158", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 18", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant18()
        {
#line 16
this.AddTwoNumbers("67", "78", "145", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 19", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant19()
        {
#line 16
this.AddTwoNumbers("53", "94", "147", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 20", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant20()
        {
#line 16
this.AddTwoNumbers("49", "95", "144", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 21", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant21()
        {
#line 16
this.AddTwoNumbers("88", "22", "110", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 22", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant22()
        {
#line 16
this.AddTwoNumbers("66", "11", "77", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 23", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant23()
        {
#line 16
this.AddTwoNumbers("98", "13", "111", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 24", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant24()
        {
#line 16
this.AddTwoNumbers("47", "67", "114", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 25", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant25()
        {
#line 16
this.AddTwoNumbers("99", "87", "186", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 26", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant26()
        {
#line 16
this.AddTwoNumbers("91", "3", "94", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 27", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant27()
        {
#line 16
this.AddTwoNumbers("85", "100", "185", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 28", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant28()
        {
#line 16
this.AddTwoNumbers("75", "94", "169", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 29", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant29()
        {
#line 16
this.AddTwoNumbers("37", "74", "111", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 30", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant30()
        {
#line 16
this.AddTwoNumbers("35", "33", "68", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add Two Numbers, Variant 31", new string[] {
                "Browser_IE",
                "Browser_Chrome",
                "Browser_Firefox"}, SourceLine=24)]
        public virtual void AddTwoNumbers_Variant31()
        {
#line 16
this.AddTwoNumbers("32", "59", "91", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
